# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravisAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_access_token', models.CharField(max_length=100)),
                ('github_userId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('userToken', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='travisaccounts',
            name='flock_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travis.User'),
        ),
    ]
